<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>e563b5db-3ae2-4396-887d-789f5e5d1a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bam-login']/bam-login/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6d7c7380-c11f-4149-83e6-3775d53a693d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5e4e010-f7a8-4948-90c1-fa5395e9cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6fdd61e6-be00-4ffe-ba19-b973368e6f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.live.bam.elderscrollsonline.com/register/account-information?version=joule&amp;language_code=en</value>
      <webElementGuid>467482ea-5371-4bef-b652-8f4501082fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b1cb830-a9cf-4813-9824-03b3f44b4eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bam-login&quot;)/bam-login[1]/iframe[1]</value>
      <webElementGuid>c2011461-8222-4c31-a6e9-d6de1bf4700e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bam-login']/bam-login/iframe</value>
      <webElementGuid>cac56b98-5a3e-4057-81b6-e3cb79847dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7d2bc6d7-ffe0-4716-81eb-fd282d6d9b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.live.bam.elderscrollsonline.com/register/account-information?version=joule&amp;language_code=en']</value>
      <webElementGuid>8d0f15c8-981e-490a-97da-87b52821e017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
