<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_usersecret_answer</name>
   <tag></tag>
   <elementGuidId>518d2b44-75ff-4f85-93cd-42b4d030346f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_secret_answer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_secret_answer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baf66b01-d244-416e-9c62-3b27d76967f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>b62f5e08-5f52-4657-a941-56fc87277f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>79206f37-afed-4a21-9abc-af9d67d22b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Answer</value>
      <webElementGuid>2b1fc3f9-03f4-47a1-859a-3664c98812cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Answer</value>
      <webElementGuid>7cdca435-d145-46da-a6de-a5f50bf9a5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4b3f3171-e1bb-4933-beeb-bbd4b9124e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>4347e490-0795-4dce-b26b-1f4b124a1da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3df7629c-777f-4d9b-b1c9-bdd211895062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[secret_answer]</value>
      <webElementGuid>cba29a39-5486-490f-a815-0cebcb88b472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_secret_answer</value>
      <webElementGuid>283ad71c-0896-4306-a932-8fd4c909d0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_secret_answer&quot;)</value>
      <webElementGuid>fe19044a-b584-4f76-a1f1-ff0350c03180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESO/Page_Login/Page_Register/iframe</value>
      <webElementGuid>31f92012-bd8a-42ae-97ce-3ee0dd31970e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_secret_answer']</value>
      <webElementGuid>54e2477e-bd5e-4b4a-86bc-e278721e3ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration']/div[10]/div/div/input</value>
      <webElementGuid>8f54b90a-54d2-4d99-8ffe-ca6caa66c707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/input</value>
      <webElementGuid>5a45b2cb-4d11-47da-8491-7b02f6741dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Answer' and @type = 'text' and @name = 'user[secret_answer]' and @id = 'user_secret_answer']</value>
      <webElementGuid>cf8c1801-6192-4f04-a446-a45bc4bc0706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
