<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pesquisar Artistas</name>
   <tag></tag>
   <elementGuidId>e6f6a19e-6e78-4ff1-901e-505fdc1c3add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce554b4c-6aa2-450c-8a92-876a2b07ce74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesquisar Artistas</value>
      <webElementGuid>3d6d969d-9d99-491a-ba0b-7eddb7ebe652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;left&quot;]/center[1]/a[2]/button[1]</value>
      <webElementGuid>ea81f3a6-abee-487e-b906-7db0ec00a759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button</value>
      <webElementGuid>93028ab9-ebce-4785-a773-9b70f97382d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Pesquisar Artistas' or . = 'Pesquisar Artistas')]</value>
      <webElementGuid>37ee0497-d6dc-4d5d-9709-d8c7de7b53fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
