<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Buy Now</name>
   <tag></tag>
   <elementGuidId>f5cb4bf3-1724-4b36-b343-b34bfce120d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buy-now-top']/div[2]/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.title.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>3118b81e-c690-45a7-93b3-6cc00ec83f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title text-center</value>
      <webElementGuid>1b65fa77-77c0-469d-882a-ead9388c1f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>837124a2-8d82-45ae-88af-6d2f3898c4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-now-top&quot;)/div[@class=&quot;col-xs-12 bnt-grade&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/h1[@class=&quot;title text-center&quot;]</value>
      <webElementGuid>ce33d46b-9927-400d-b3d1-c3730085ffb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buy-now-top']/div[2]/div/div/div/h1</value>
      <webElementGuid>5c1d0d04-5bb2-475b-950b-535ca7798ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>0f0c326d-9fa2-4182-825a-d65d1d39e67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Buy Now' or . = 'Buy Now')]</value>
      <webElementGuid>b7837237-6b4a-429e-9b44-a482f1125977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
