<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Classes</name>
   <tag></tag>
   <elementGuidId>e8590575-6e97-4de0-85c9-d8982699c12f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carousel-half-chunk']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ea74e805-6150-4075-818c-6c8b31ccc39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a466af34-369f-4d36-a564-d540fae040a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Classes</value>
      <webElementGuid>fcc7f026-d42a-4f7b-b0a1-f29fda954907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel-half-chunk&quot;)/div[@class=&quot;square s1&quot;]/div[@class=&quot;square-inner
							m-middle			
							m-center			
							d-middle			
							d-left&quot;]/h1[@class=&quot;h2&quot;]</value>
      <webElementGuid>a92afb71-ddb2-4ff8-baab-23e7e9c0d14d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel-half-chunk']/div/div/h1</value>
      <webElementGuid>65a25983-6a66-4aee-8673-112e45ba0530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f7f46e1e-ee3d-4212-8495-6d9176b0d2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Classes' or . = 'Classes')]</value>
      <webElementGuid>74cdbbd8-65cb-41e2-af73-0868ac0d156c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
