<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_s-image</name>
   <tag></tag>
   <elementGuidId>495b7c1c-41e3-4ba3-b6ce-04af5c9ea8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div[3]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c99547d-a077-4c91-893b-861d5c9c3583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>71d0d5d8-fe3c-4713-b33b-19abc5131f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xs</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/6927a0824cd5e0943343081377d1bf0a.jpg</value>
      <webElementGuid>ced4c0dc-c4a4-475e-ad31-b4e99645de4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sm</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/5385e82ed1eaf9c0ad6e4d6d32535868.jpg</value>
      <webElementGuid>0fa6650e-a12e-4b85-bda6-c5dacb908c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-md</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/9b8f7263064e36c67c68cd79cd571f12.jpg</value>
      <webElementGuid>b0fc8bc6-50af-4de8-8943-50042e5758f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lg</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/6a02bedb78362052730ab4a53d61feb4.jpg</value>
      <webElementGuid>8367b9a8-b927-4a2b-aae9-9c32da342e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xlg</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/2158fd033b5345203f6d42033173d0a6.jpg</value>
      <webElementGuid>df5dd43d-0cea-4150-b0b3-f3a1e7c3e2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/6a02bedb78362052730ab4a53d61feb4.jpg</value>
      <webElementGuid>4582f2bb-526c-4d54-a650-7e38c285ab5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;clearfix row-0 row-catch is-row&quot;]/div[@class=&quot;col-0 is-col&quot;]/div[@class=&quot;feature-box
			no-padding&quot;]/div[@class=&quot;feature-parallax&quot;]/div[@class=&quot;feature-image-wrap feature-parallax-item&quot;]/div[@class=&quot;feature-image-box&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>a56c4044-56fa-4021-82c3-71c8cf944b87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div[3]/div/div/div/img</value>
      <webElementGuid>c885563c-4645-4068-8e4e-436bf762d936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/6a02bedb78362052730ab4a53d61feb4.jpg')]</value>
      <webElementGuid>a631b396-0bff-4ddb-a47c-aac024141206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>caaf4482-820c-4ea6-8605-554af2334785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://esosslfiles-a.akamaihd.net/ape/uploads/2023/05/6a02bedb78362052730ab4a53d61feb4.jpg']</value>
      <webElementGuid>956ad5a9-067c-4637-82bf-6149ecc71510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
