<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>250e4b07-4f76-4b21-89b4-e83279cc472e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:submitSignInForm();' and @id = 'submit-sign-in' and (text() = 'Sign In' or . = 'Sign In') and @ref_element = 'Object Repository/ESO/Page_Login/iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-sign-in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submit-sign-in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f23aaf30-622e-42cc-a9cd-cb8396c1d4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:submitSignInForm();</value>
      <webElementGuid>378c685a-e7a9-4daa-87a7-1dc673958d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default submit-form</value>
      <webElementGuid>328fd620-271d-4e11-873d-ef8290e801f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-sign-in</value>
      <webElementGuid>7a2481ee-7c81-495e-879e-b09860953cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>24643e19-6cf6-4bde-9214-27112d67ddc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-sign-in&quot;)</value>
      <webElementGuid>61e6048a-9eb0-48d3-a027-9fa504c7d46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESO/Page_Login/iframe</value>
      <webElementGuid>80a2d716-809e-4dc2-a32a-1f8b247e8c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submit-sign-in']</value>
      <webElementGuid>807ef32d-049a-4834-a2e1-ff1185179313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sign-in-form']/div[6]/a</value>
      <webElementGuid>a372a29c-fae4-4dfe-b78a-c009caf2efe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign In')]</value>
      <webElementGuid>b5c7d39c-202a-48f2-b6c9-338e2166ec48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:submitSignInForm();')]</value>
      <webElementGuid>42861006-1a04-4ef0-b784-cd064959b7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>d86c46a0-1c24-45b7-a205-d87f0eaa6c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:submitSignInForm();' and @id = 'submit-sign-in' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>443e906a-2035-471f-96b1-025411518f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
