<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>250e4b07-4f76-4b21-89b4-e83279cc472e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-sign-in</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:submitSignInForm();' and @id = 'submit-sign-in' and (text() = 'Sign In' or . = 'Sign In')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submit-sign-in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e3f8947-bb48-417a-8aef-46f022544676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:submitSignInForm();</value>
      <webElementGuid>9ea80529-3036-485a-b9c7-4fb8414c3718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default submit-form</value>
      <webElementGuid>75afa564-e537-4001-bfc8-dc24b0d1f90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-sign-in</value>
      <webElementGuid>804fdc96-a046-430d-afe7-87a6af6e8c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>3f72cada-576b-4fd9-97ec-473aeb217b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-sign-in&quot;)</value>
      <webElementGuid>1919e733-7401-406d-bbae-9f60d525b2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESO/Page_Login/Login_Form</value>
      <webElementGuid>11ef54ab-192c-485b-8e54-cfa125c75b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submit-sign-in']</value>
      <webElementGuid>28363db4-c81c-4020-ae63-501ecaf56b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sign-in-form']/div[6]/a</value>
      <webElementGuid>5f04a57f-17c3-41e8-b13e-7efd0be0f1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign In')]</value>
      <webElementGuid>1d4ca430-2dfc-4427-9884-6b4a8f3ae6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:submitSignInForm();')]</value>
      <webElementGuid>82ba4880-182f-4f96-a9a2-23b487a5b088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>f59ff12e-fe1a-4964-9834-3b9b76151ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:submitSignInForm();' and @id = 'submit-sign-in' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>4a91f39e-7885-4575-beb9-629d2aa5e3cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
