<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In</name>
   <tag></tag>
   <elementGuidId>250e4b07-4f76-4b21-89b4-e83279cc472e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submit-sign-in']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:submitSignInForm();' and @id = 'submit-sign-in' and (text() = 'Sign In' or . = 'Sign In') and @ref_element = 'Object Repository/ESO/Page_Login/iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-sign-in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1253224-5ccd-4160-888e-4b224acb0fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:submitSignInForm();</value>
      <webElementGuid>37bb2243-ac03-4df1-94f9-6b2e2a527bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default submit-form</value>
      <webElementGuid>6bb65758-b68f-4234-81b6-3aefc76512fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-sign-in</value>
      <webElementGuid>2e8a0f61-728a-4513-b937-50988f957e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>bec21769-57eb-4a32-a433-80252cc57300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-sign-in&quot;)</value>
      <webElementGuid>1dcb0e01-81de-423f-834a-81f9fad11d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESO/Page_Login/iframe</value>
      <webElementGuid>15cf0992-1312-487a-8222-0422625f152e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submit-sign-in']</value>
      <webElementGuid>3f794dfc-03a4-4e8d-bd36-2c1cbcb6e15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sign-in-form']/div[6]/a</value>
      <webElementGuid>a938ee19-e04a-45aa-8a5a-233e69669caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign In')]</value>
      <webElementGuid>3ea216ea-6d47-4e2a-878d-dc341a414c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:submitSignInForm();')]</value>
      <webElementGuid>de94b194-1f44-49a8-8469-9f4b80fc96a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>33ca8803-81f5-4508-aa96-f5cb17c9d356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:submitSignInForm();' and @id = 'submit-sign-in' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>ab4dedea-5c0f-4d05-bce6-253b1e4d8212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
