<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>e7c98dd6-0ec8-4e53-87c6-d550fb2aa635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bam-login']/bam-login/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>40878513-b804-44df-8114-724e162b6039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f94dd74-70de-41f1-b757-073bba2f401e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e61e2f01-544d-472f-92e5-9692b9487a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en</value>
      <webElementGuid>46aba5cd-7983-4ea9-b5f2-84c50ea61d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48b6c6b5-a2e1-45a9-87bf-027a58889de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bam-login&quot;)/bam-login[1]/iframe[1]</value>
      <webElementGuid>54a08ef1-c407-400a-9ff6-399e0c2df7ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bam-login']/bam-login/iframe</value>
      <webElementGuid>3d99f5a5-6e75-41b7-a5d2-5ed240422154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ee444c90-3eaa-4914-9872-2843917eb83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en']</value>
      <webElementGuid>59abb75d-a136-4579-a1e5-937bb1b93050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bam-login/iframe</value>
      <webElementGuid>0f9d1766-148a-4c97-af71-cd9a130ff71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
