<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>e7c98dd6-0ec8-4e53-87c6-d550fb2aa635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>bam-login > iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bam-login']/bam-login/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>47bfd45c-1c5a-4149-a6ed-663307bc90f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6fc6b8f5-7922-4c5a-b197-e350584535b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>88408642-81d5-4acd-b20a-f149819ef80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en</value>
      <webElementGuid>033e7293-6974-4c87-987e-3aaa254005fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b32d91d0-d823-4230-ad28-a163a9b705cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bam-login&quot;)/bam-login[1]/iframe[1]</value>
      <webElementGuid>911c163c-6e2c-4648-9408-06ec6dd5f538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bam-login']/bam-login/iframe</value>
      <webElementGuid>045647f6-fde1-48b7-bb56-bac24202d93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bam-login/iframe</value>
      <webElementGuid>0f9d1766-148a-4c97-af71-cd9a130ff71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en']</value>
      <webElementGuid>6a576835-1414-4b64-b40d-116545b91d76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
