<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_userremember_me</name>
   <tag></tag>
   <elementGuidId>a4bfaf16-2fff-436b-8cbe-1e8d5a4f0a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#persist-signin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='persist-signin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e456072-f3a9-481b-a9b9-894992764b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>persist-signin</value>
      <webElementGuid>e27825a6-7075-41b1-b091-9269a3e207a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[remember_me]</value>
      <webElementGuid>0fe057b3-e778-4247-8510-1f03ed73a3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>46e54eab-c94f-4598-b7bb-9fbc5436ce71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Keep Me Signed In</value>
      <webElementGuid>b0b7f722-a44b-4869-8257-bc1ca68c7ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;persist-signin&quot;)</value>
      <webElementGuid>6946d0d4-e3b1-40ce-b20c-67512455f22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESO/Page_Login/Login_Form</value>
      <webElementGuid>8361114f-3fc1-4905-b637-b0b7a99487e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='persist-signin']</value>
      <webElementGuid>805dc8cf-1f1e-4e2c-8703-775d5a89d179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sign-in-form']/div[5]/span/input</value>
      <webElementGuid>9ca496fc-5282-4d0a-ac41-088faee130bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>f4f89d44-170e-49a9-9b89-3abf6054eb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'persist-signin' and @name = 'user[remember_me]' and @type = 'checkbox']</value>
      <webElementGuid>59c48914-8ca6-4963-9764-f5df2f1b9ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
