<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_Form</name>
   <tag></tag>
   <elementGuidId>e7c98dd6-0ec8-4e53-87c6-d550fb2aa635</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Login/Login_Form.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Login/Login_Form.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>bam-login > iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bam-login']/bam-login/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>aad163d0-e0b2-46eb-be73-ffabae281f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90b9bce0-42ac-4eb8-93e2-8d7e1fe4a48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>047e32c4-d0dc-4d48-97e6-0cfd3a8ca485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en</value>
      <webElementGuid>9951c207-4e90-41fd-ab9c-6b806f42599e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d8ff724-dbdd-4983-8a11-95a86a5045f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bam-login&quot;)/bam-login[1]/iframe[1]</value>
      <webElementGuid>4a69f61d-21d2-4580-9840-8ebf298a365f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bam-login']/bam-login/iframe</value>
      <webElementGuid>111af217-21f4-4a93-a560-40335ca85e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bam-login/iframe</value>
      <webElementGuid>619c440f-45c2-4a64-a986-07f2fd1d2761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.live.bam.elderscrollsonline.com/login?version=joule&amp;language_code=en']</value>
      <webElementGuid>2ee857f6-f076-45f1-ac5c-89c929a5d6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
