<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_C1500</name>
   <tag></tag>
   <elementGuidId>f0b6bb07-082a-46e8-8674-53bb80778bea</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Buy Crowns/img_C1500.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Buy Crowns/img_C1500.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://esosslfiles-a.akamaihd.net/cms/2020/10/26c0bd962dd395ebdde57cb784e4ce1d.jpg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buy-crowns-page-1']/a[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c49aeb1-020e-48b3-aae6-0e417672b70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>4d72ba0e-c7d4-4eeb-9e03-4938f6d03460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/cms/2020/10/26c0bd962dd395ebdde57cb784e4ce1d.jpg</value>
      <webElementGuid>beefe5b9-aec4-405c-ba86-8a06f41a5f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-crowns-page-1&quot;)/a[@class=&quot;across-5 pull-left text-center zl-link gl-link-checked&quot;]/div[@class=&quot;crown-pack&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>b42011b4-1274-4a79-a70c-abb03d714b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buy-crowns-page-1']/a[3]/div/img</value>
      <webElementGuid>79f95ee1-373f-426e-b4d0-68d6533d5727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://esosslfiles-a.akamaihd.net/cms/2020/10/26c0bd962dd395ebdde57cb784e4ce1d.jpg')]</value>
      <webElementGuid>77d0a5da-5be8-4dcb-8a5b-7f61d5e8b1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]/div/img</value>
      <webElementGuid>674ef4a6-7ee4-4dda-abb3-f3ffd5b83654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://esosslfiles-a.akamaihd.net/cms/2020/10/26c0bd962dd395ebdde57cb784e4ce1d.jpg']</value>
      <webElementGuid>f895afb8-3588-4271-8f44-47013645a178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
