<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_As an Arcanist, knowledge is the key to p_8adf88</name>
   <tag></tag>
   <elementGuidId>d85fc046-3c8d-482a-8d27-d46cdc7d03e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pip-arcanist']/div/div/div/div/div[2]/div/div[2]/p[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b2984870-fc71-4319-a708-3f9aa294f124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>As an Arcanist, knowledge is the key to power beyond understanding.  </value>
      <webElementGuid>8d4bfca6-526f-415e-8edc-7e778933989c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pip-arcanist&quot;)/div[@class=&quot;feature-box&quot;]/div[@class=&quot;feature-content-box&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-10 col-sm-offset-1 col-md-5 col-md-offset-0 detail-top-text&quot;]/p[4]</value>
      <webElementGuid>0d9739e7-30da-4db9-bcc5-d2994654452d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pip-arcanist']/div/div/div/div/div[2]/div/div[2]/p[4]</value>
      <webElementGuid>2ccbed31-5de0-4c70-9954-c97a206e9be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>6c973e51-2861-47d3-9d6e-f43552190344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'As an Arcanist, knowledge is the key to power beyond understanding.  ' or . = 'As an Arcanist, knowledge is the key to power beyond understanding.  ')]</value>
      <webElementGuid>0170e960-b4bd-42fb-9a55-fc7c2a8a280d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
