<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_UpdatesDLC</name>
   <tag></tag>
   <elementGuidId>64654638-1b78-4a4c-8ca4-7d29a456f575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='universal-nav']/div/div/div[6]/div/div[2]/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbd51acb-7363-4a18-9eeb-b99cc7b3e2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-us/updates</value>
      <webElementGuid>6e1ae896-8b04-4782-8416-4afab2fa66e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d41fc55e-bd82-4f39-8651-ac184e43a036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gl-link-internal gl-link-checked</value>
      <webElementGuid>77ab65b4-3363-4d17-bb05-46ada30e39a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Updates/DLC</value>
      <webElementGuid>df4a9730-d64d-42c0-b235-f1fdbdb22b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;universal-nav&quot;)/div[@class=&quot;un-wrapper-wrap&quot;]/div[@class=&quot;un-wrapper&quot;]/div[@class=&quot;un-mobile-wrapper&quot;]/div[@class=&quot;un-mobile-box&quot;]/div[@class=&quot;un-third-level&quot;]/div[@class=&quot;third third-1                                      active&quot;]/div[@class=&quot;links&quot;]/div[@class=&quot;link&quot;]/a[@class=&quot;gl-link-internal gl-link-checked&quot;]</value>
      <webElementGuid>0db2638e-4379-444e-af4a-ac2c8719d79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-nav']/div/div/div[6]/div/div[2]/div/div/div[3]/a</value>
      <webElementGuid>ca47f424-b8b1-496c-83d6-8877bfb81f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Updates/DLC')]</value>
      <webElementGuid>38ef59dd-8827-4318-b188-d295b54257a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-us/updates')]</value>
      <webElementGuid>fa6382d7-86d1-4460-bf32-9ffea47cbe41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/a</value>
      <webElementGuid>c296b5ea-a2ca-4bf2-9bd8-62fdae869c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-us/updates' and (text() = 'Updates/DLC' or . = 'Updates/DLC')]</value>
      <webElementGuid>9240486e-7c00-49be-97ad-4834451e46cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
