<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_youtube background-click-link zl-link con_6a1de9</name>
   <tag></tag>
   <elementGuidId>9ffec65f-6a0b-4da4-9e86-de1b1dc84177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='updates-header']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.youtube.background-click-link.zl-link.content-gate.gl-link-checked</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc86d661-6076-4097-83b0-958d43202769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>youtube background-click-link zl-link content-gate gl-link-checked</value>
      <webElementGuid>ed32add8-7bdb-404f-8f3c-5ba37e7d5ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e0964baf-031c-4b0f-8fa1-03435b467052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zl-type</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>5bb30795-b58c-4d26-b2ac-fd264fa8773f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zl-category</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>fc39ffb2-b965-4a39-aa59-83f43aa8ffd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://youtube.com/embed/ojDai6GBR8Y?autoplay=1&amp;rel=0</value>
      <webElementGuid>d66db734-eb32-4125-b230-c09d8ffae389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>103febad-5880-46ea-acbb-f29b65e84822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updates-header&quot;)/div[1]/div[@class=&quot;content-box&quot;]/a[@class=&quot;youtube background-click-link zl-link content-gate gl-link-checked&quot;]</value>
      <webElementGuid>92f3d204-d623-4da5-8f35-115a64140b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updates-header']/div/div/a</value>
      <webElementGuid>ce2de461-bbf0-4ef6-ba95-b3ec173dc5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://youtube.com/embed/ojDai6GBR8Y?autoplay=1&amp;rel=0')]</value>
      <webElementGuid>554fc725-6153-4d3b-bd0f-8a52f794d5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/a</value>
      <webElementGuid>ab943e49-c6d2-4d2d-ab26-fdd10fe362a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://youtube.com/embed/ojDai6GBR8Y?autoplay=1&amp;rel=0']</value>
      <webElementGuid>550254ee-7183-459c-98b7-0d02c28cd049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
