<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_youtube background-click-link zl-link con_6a1de9</name>
   <tag></tag>
   <elementGuidId>9ffec65f-6a0b-4da4-9e86-de1b1dc84177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.youtube.background-click-link.zl-link.content-gate.gl-link-checked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='updates-header']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f393ec2-9622-42fb-9465-a8a57636fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>youtube background-click-link zl-link content-gate gl-link-checked</value>
      <webElementGuid>cecb393b-4ded-48d0-9af8-64d5323cf495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>410c97d7-accb-4414-8f34-85a9545c3a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zl-type</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>25db8b9c-9160-4cfb-89d0-109502519e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zl-category</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>7cc3150e-adab-4260-9242-fa53d7c8fedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://youtube.com/embed/ojDai6GBR8Y?autoplay=1&amp;rel=0</value>
      <webElementGuid>70d79977-9b0c-4957-9424-9c1132f86fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>99aa875f-e7ba-4f40-a18b-6ddb25238034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updates-header&quot;)/div[1]/div[@class=&quot;content-box&quot;]/a[@class=&quot;youtube background-click-link zl-link content-gate gl-link-checked&quot;]</value>
      <webElementGuid>81c2dcbb-fbc5-48da-9de5-6188a18766cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updates-header']/div/div/a</value>
      <webElementGuid>9a92b594-a8f7-4911-9b20-1d44a90e287f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://youtube.com/embed/ojDai6GBR8Y?autoplay=1&amp;rel=0')]</value>
      <webElementGuid>a4f6e1a3-1c8f-4eb4-9a85-c56ac3b57ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/a</value>
      <webElementGuid>48ecdb10-18fb-45a8-9346-12bcb118838a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://youtube.com/embed/ojDai6GBR8Y?autoplay=1&amp;rel=0']</value>
      <webElementGuid>840d38f5-2bc2-4bd4-a889-436a553d5b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
