<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-lg fa-times</name>
   <tag></tag>
   <elementGuidId>b117638e-79bc-4263-a5f6-567369f657c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='universal-nav']/div/div/div[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-lg.fa-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c8d5e70f-2a60-4d32-8ca4-e6b4e4a98922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-lg fa-times</value>
      <webElementGuid>777eccd2-0775-4697-b539-b78f19a0b8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b179fcca-0472-4701-8e08-9cd2d2cd1ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;universal-nav&quot;)/div[@class=&quot;un-wrapper-wrap&quot;]/div[@class=&quot;un-wrapper&quot;]/div[@class=&quot;close-mobile un-top&quot;]/i[@class=&quot;fa fa-lg fa-times&quot;]</value>
      <webElementGuid>f03a7d5f-d5cb-4fac-a674-5e244f28d283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-nav']/div/div/div[3]/i</value>
      <webElementGuid>0ff82b9f-3968-4a64-bfff-007aede7d9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>a077e056-0dcc-4e8c-9e51-aa63d2bd25b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
