<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-responsive</name>
   <tag></tag>
   <elementGuidId>a514ae29-1272-4bb6-9e28-5763e9910ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buy-crowns-nav']/div/div/a[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15de29d2-3977-47d1-86ac-12be26d7bb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>389a3a89-d4ac-4aac-895e-fdedc3e66af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://esosslfiles-a.akamaihd.net/cms/2020/10/68b9660426408eb59110b9902d3dab8f.jpg</value>
      <webElementGuid>d30e5a7e-e05c-4ffd-a6aa-43156d8354d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-crowns-nav&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/a[@class=&quot;across col-xs-12 col-md-2 text-center zl-link gl-link-checked&quot;]/div[@class=&quot;crown-pack&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>1c29404b-c41c-4769-9246-167871208ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buy-crowns-nav']/div/div/a[2]/div/img</value>
      <webElementGuid>41e8e829-acca-4ca2-82dc-f521d920e178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://esosslfiles-a.akamaihd.net/cms/2020/10/68b9660426408eb59110b9902d3dab8f.jpg')]</value>
      <webElementGuid>7d38fed1-f868-450e-9733-436fdf1458a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/img</value>
      <webElementGuid>068e58eb-ddf7-465d-81c3-3ff2091d9def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://esosslfiles-a.akamaihd.net/cms/2020/10/68b9660426408eb59110b9902d3dab8f.jpg']</value>
      <webElementGuid>003eaf0d-df8d-4f63-999d-a29b8cd79bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
