<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dev Tracker</name>
   <tag></tag>
   <elementGuidId>7ec8a6cb-ae57-4c7d-a4d7-0e42130f5c49</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/en/tracker' and (text() = '
                                                                                                              Dev Tracker                          ' or . = '
                                                                                                              Dev Tracker                          ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.link.picked > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='universal-nav']/div/div/div[6]/div/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ed4d805-a215-4f2b-99b5-57feee9ada93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4305a3c1-5f13-45ba-a67a-ded3f2efff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>bdd059ad-56b4-4905-8c34-e3fd250c7c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99620bf4-a1df-42f2-83a2-a53ccf0152ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c835cf7e-dada-4215-91a6-7a79a8ac8172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d09c5083-acf8-436e-bcf6-594cb55a7dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/tracker</value>
      <webElementGuid>bef77df6-78de-4e30-8e1b-cf82077f7d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                              Dev Tracker                          </value>
      <webElementGuid>fe3ec4cf-507d-4aed-9674-5cb863a76b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;universal-nav&quot;)/div[@class=&quot;un-wrapper-wrap&quot;]/div[@class=&quot;un-wrapper&quot;]/div[@class=&quot;un-mobile-wrapper&quot;]/div[@class=&quot;un-mobile-box&quot;]/div[@class=&quot;un-second-level&quot;]/div[@class=&quot;links&quot;]/div[@class=&quot;link picked&quot;]/a[1]</value>
      <webElementGuid>99908c10-ec6b-42d4-a8c1-675bc3fd88b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='universal-nav']/div/div/div[6]/div/div/div/div[3]/a</value>
      <webElementGuid>ee142fe2-83a6-4a0d-91ed-901e6df9bd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dev Tracker')]</value>
      <webElementGuid>daa543c4-6e36-4d1a-9f9c-90517fab167e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/tracker')]</value>
      <webElementGuid>98ce7c6e-559a-4540-89b2-e916ce54fbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]/a</value>
      <webElementGuid>281b1fce-13d6-4e7a-be40-9191ab1f495d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/tracker' and (text() = '
                                                                                                              Dev Tracker                          ' or . = '
                                                                                                              Dev Tracker                          ')]</value>
      <webElementGuid>663851c9-592f-482a-a87a-f3b66c830f0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
