<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category_Header</name>
   <tag></tag>
   <elementGuidId>b2716ed2-a95a-47d1-b0ad-1e886705e195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Content&quot;)/h1[@class=&quot;H&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.H</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Content']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>aada951b-6e1c-43ac-9e07-bd02c4daab3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>5d37074b-57f0-452b-a7f1-7d40383f8697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dev Tracker</value>
      <webElementGuid>6e22f6aa-c2b5-46a8-b24b-0c7dce7bed6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/h1[@class=&quot;H&quot;]</value>
      <webElementGuid>7d48d29f-8456-4c84-a99f-556acd1e451d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/h1</value>
      <webElementGuid>b13a8301-b0fe-473a-b467-0a47a3ae10fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h1</value>
      <webElementGuid>d4d9947a-b6ee-4f8c-9513-4c576c823bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Dev Tracker' or . = 'Dev Tracker')]</value>
      <webElementGuid>fb48ce49-7c4e-47c0-ad2c-811a99111c98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
