<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_userscreen_name</name>
   <tag></tag>
   <elementGuidId>b6909ed8-12e9-411e-9b37-8a54ece4fb10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_screen_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_screen_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63ff3552-12b1-466c-a31c-2753522c7d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_screen_name</value>
      <webElementGuid>e9c88400-f1ed-40fe-a0ce-6b89e39cd63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>878c8201-0e5a-4865-b618-665388ca646e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>UserID</value>
      <webElementGuid>5900a198-6a4b-46d6-af42-2a9826cf8c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>UserID</value>
      <webElementGuid>0475100d-a985-47a9-8ed0-914f4b6c1894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2877dac9-4f7c-4934-8b5e-40bd1ccebf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e775363d-cf3f-4951-9f4a-7ca9b2a876b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3fd844e3-de12-4af8-a480-eb2e7cb8a991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33d34b02-16b4-4edc-abfc-381fe28694d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[screen_name]</value>
      <webElementGuid>da30914d-ef05-49d9-b66d-4517c197ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_screen_name&quot;)</value>
      <webElementGuid>474d1493-6832-45ea-b516-1127298481b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_screen_name']</value>
      <webElementGuid>d2be20e6-ad54-4d48-a1af-cda41948d233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user_id_input_div']/input</value>
      <webElementGuid>71ce6b8e-a2c7-4a7b-bc25-87ee1dd1f080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>b6589b98-d797-4ded-bb36-f3a40d35e845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_screen_name' and @placeholder = 'UserID' and @type = 'text' and @name = 'user[screen_name]']</value>
      <webElementGuid>c0d09b1d-3e82-4712-accd-368dd5bbf904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
