<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_userpassword_confirmation</name>
   <tag></tag>
   <elementGuidId>2aee5806-1590-42e7-96eb-16b0ca857a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_password_confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_password_confirmation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ae5f67a-bf28-4383-accb-641beed7bc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password_confirmation</value>
      <webElementGuid>f1b3f4e3-3e30-4298-a503-440b957d72c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control password</value>
      <webElementGuid>d67a026b-2264-46ab-9b8d-81d74c967bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[password_confirmation]</value>
      <webElementGuid>3dffcbff-8bb1-439d-b203-562e0e9705bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7bd22f66-36fa-4d97-ab25-23d1b7e24ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>9f068243-9df7-444c-840d-92f1fd0e3b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>57e34010-b95f-4ada-bf28-b95ea4b625a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm password</value>
      <webElementGuid>fddb0a95-0be0-4a4b-b4bc-ca7abb567105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Confirm password</value>
      <webElementGuid>15d5e6d4-66a2-46c9-b7ed-fe1fd64eee53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password_confirmation&quot;)</value>
      <webElementGuid>89f5a0bb-093b-4fe3-8c3a-0862defd5ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password_confirmation']</value>
      <webElementGuid>8519d545-7bd0-4dc9-a6b3-ad03205a136f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration']/div[8]/div/div/input</value>
      <webElementGuid>f7598b1a-b950-43f3-9cd4-6d377fead976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>5ca7d712-654c-49d5-be6c-2296c3c69e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_password_confirmation' and @name = 'user[password_confirmation]' and @type = 'password' and @placeholder = 'Confirm password']</value>
      <webElementGuid>1edb13c4-2ff6-4708-9469-c6c829dea02e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
