<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_useremail_confirmation</name>
   <tag></tag>
   <elementGuidId>d76a6ba4-7192-46b4-9519-3710808b4e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_email_confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_email_confirmation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a369266b-c22b-4cf3-a158-f6c99484b292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_email_confirmation</value>
      <webElementGuid>57e8e74d-60f3-4506-be10-e7175c67fd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5c280545-2c65-484a-a60b-d5686715adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[email_confirmation]</value>
      <webElementGuid>46eb54e8-4410-4904-807f-d977d5b6866b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4be967eb-fab6-49dc-b8ad-b4a0949a56de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm email</value>
      <webElementGuid>cfd7eb05-aef5-4ac7-a8be-a7e21edb01bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Confirm email</value>
      <webElementGuid>3cea2e18-c7ca-4155-a5ed-d9bf14e25670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d17a5148-b356-40e4-af1a-c2ec6de328db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_email_confirmation&quot;)</value>
      <webElementGuid>b14dc26b-af6f-40d6-8aca-51692e12d781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_email_confirmation']</value>
      <webElementGuid>16f3dc10-3ba9-4f9b-b710-7372d434f456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration']/div[6]/div/div/input</value>
      <webElementGuid>9f7b61cb-2f1f-4641-b25b-9924beba31cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>bc59fa69-5028-4797-b867-9bcd6e2dde49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_email_confirmation' and @name = 'user[email_confirmation]' and @placeholder = 'Confirm email' and @type = 'email']</value>
      <webElementGuid>6ee4ec6a-33ed-4bca-842d-a21eff4ddf55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
