<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data_Inicio</name>
   <tag></tag>
   <elementGuidId>71f2b992-6e9d-4128-8741-6d75ae05c514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Data_Inicio&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Data_Inicio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd42f596-0431-4c19-a55c-d193f00f51ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c1b817cc-532b-4bd8-8116-e282405d99bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Data_Inicio</value>
      <webElementGuid>e027e9bf-9e08-4a00-b41b-0b06f5d04699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Data de Inicio</value>
      <webElementGuid>3d677f76-2a6f-4df9-9782-9830fee114ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;left&quot;]/form[1]/input[6]</value>
      <webElementGuid>53f77782-ad60-47ae-aa7e-8cfbdf16d0ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Data_Inicio']</value>
      <webElementGuid>d1b19bfa-8a0e-4c10-845f-c76ff9f792c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>21899168-665e-4faf-a466-44cc72f953a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'Data_Inicio' and @placeholder = 'Data de Inicio']</value>
      <webElementGuid>7bc9e70d-7c4d-461a-8d7b-95f3dfb4b161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
