<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data_Fim</name>
   <tag></tag>
   <elementGuidId>b95d9ef1-835f-4dbc-8b8e-aa18882c46e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Data_Fim&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Data_Fim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9843aae-1b2c-4bbb-9634-f8ffb8c28b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e4c835fe-eaa3-4fc0-ac9a-712529e85a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Data_Fim</value>
      <webElementGuid>d71ef12f-2fa2-4815-8d90-38782a692809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Data de Fim</value>
      <webElementGuid>a482b238-d60b-4887-89d3-5cb90b9621bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;left&quot;]/form[1]/input[7]</value>
      <webElementGuid>0c309463-5c83-46b8-a577-ee5f7d39b0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Data_Fim']</value>
      <webElementGuid>c3c81969-f29e-4b79-bce9-bd8a854ec572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>37536802-088a-43c1-98fc-5a7712facea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'Data_Fim' and @placeholder = 'Data de Fim']</value>
      <webElementGuid>8a669110-df04-40cf-a6dc-d704823d905e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
